### ISSUE TITLE
How much is your Colord Manga picture?

### ISSUE THREAD

**Issue by HyperSimon** [chandlerbing65nm/Black-Clover-Manga-Colorization-with-GAN#2]
Hello, how many colored pictures do you have for this data set of One Piece?

I am doing the same thing, the difference from yours is that my color comics have a one-to-one correspondence with black and white comics, there are about 2000 color comics, and the number of black and white pictures is the same, I am a newbie, please use yours Can the model be trained to get better results?

**Comment by chandlerbing65nm** [comment]
@HyperSimon The GAN architecture I used is CycleGAN, which is designed for unpaired dataset, but you can still use it. I assume it would not be efficient.

I suggest look for another GANs that are used with paired dataset (one-one correspondence). Try using [Pix2Pix](https://github.com/open-mmlab/mmgeneration/blob/master/configs/pix2pix/README.md).

**Comment by HyperSimon** [comment]
@chandlerbing65nm I went through a lot of detours, thank you very much for your advice. I will close this issue.
